# Default values for etcd-cluster-migrator-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

name: etcd-cluster-migrator

configmap:
  baseDomain: "i5mc9.k8s.ginger.eu-west-1.aws.gigantic.io"

app:
  baseDomain: "i5mc9.k8s.ginger.eu-west-1.aws.gigantic.io"

  userID: 0
  groupID: 0

  resources:
    limits:
      memory: 100Mi
    requests:
      cpu: 75m
      memory: 100Mi

image:
  name: giantswarm/etcd-cluster-migrator
  tag: "[[ .Version ]]"
  pullPolicy: IfNotPresent
  registry: quay.io
