version: 2.1
orbs:
  architect: giantswarm/architect@0.8.5

workflows:
  build:
    jobs:
      - architect/go-build:
          name: go-build-etcd-cluster-migrator
          binary: etcd-cluster-migrator
          filters:
            # Trigger the job also on git tag.
            tags:
              only: /^v.*/

      - architect/push-to-docker:
          context: "architect"
          name: push-etcd-cluster-migrator-to-quay
          image: "quay.io/giantswarm/etcd-cluster-migrator"
          username_envar: "QUAY_USERNAME"
          password_envar: "QUAY_PASSWORD"
          requires:
            - go-build-etcd-cluster-migrator
          filters:
            # Trigger the job also on git tag.
            tags:
              only: /^v.*/

      - architect/push-to-docker:
          context: "architect"
          name: push-etcd-cluster-migrator-to-aliyun
          image: "registry-intl.cn-shanghai.aliyuncs.com/giantswarm/etcd-cluster-migrator"
          username_envar: "ALIYUN_USERNAME"
          password_envar: "ALIYUN_PASSWORD"
          requires:
            - go-build-etcd-cluster-migrator
          filters:
            # Trigger the job also on git tag.
            tags:
              only: /^v.*/
