apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: {{ .Values.name }}-job
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.name }}-job
    giantswarm.io/service-type: "managed"
spec:
  privileged: false
  allowPrivilegeEscalation: false
  volumes:
    - 'configMap'
  hostNetwork: false
  hostIPC: false
  hostPID: true
  runAsUser:
    rule: 'RunAsAny'
  seLinux:
    rule: 'RunAsAny'
  supplementalGroups:
    rule: 'RunAsAny'
  fsGroup:
    rule: 'RunAsAny'
  readOnlyRootFilesystem: false
