apiVersion: kyverno.io/v2alpha1
kind: PolicyException
metadata:
  name: {{ include "resource.default.name" . }}-exceptions
  namespace: {{ include "resource.default.namespace" . }}
spec:
  exceptions:
  - policyName: disallow-host-path
    ruleNames:
    - host-path
    - autogen-host-path
  match:
    any:
    - resources:
        kinds:
        - Job
        - Pod
        namespaces:
        - {{ include "resource.default.namespace" . }}
        names:
        - {{ .Chart.Name }}*
