apiVersion: kyverno.io/v2alpha1
kind: PolicyException
metadata:
  name: {{ .Values.name }}-exceptions
  namespace: {{ .Release.Namespace }}
spec:
  exceptions:
  - policyName: disallow-host-path
    ruleNames:
    - host-path
    - autogen-host-path
  match:
    any:
    - resources:
        kinds:
        - Job
        - Pod
        namespaces:
        - {{ .Release.Namespace }}
        names:
        - {{ .Chart.Name }}*
